name: Hourly Task
on:
  # 1. 按钮触发：让你可以随时手动点一下运行
  workflow_dispatch: 
  
  # 2. 定时触发：每 60 分钟尝试一次（作为后台自动运行）
  schedule:
    - cron: '*/60 * * * *'
jobs:
  timed-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: echo "The time is $(date)"
