name: Deploy MkDocs Site
on:
  workflow_dispatch:
  push:
    branches: ["main"]

# 统一使用 Pages 权限
permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build Site
        # 仅仅是 build，不执行 deploy 命令，不产生新分支
        run: mkdocs build 

      - name: Upload Artifact
        # 将生成的 site 文件夹（MkDocs 默认输出目录）打包
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
